#! /bin/sh
### BEGIN INIT INFO
# Provides:          teamcity-agent
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Should-Start:      $named $syslog $time
# Should-Stop:       $named $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      S 0 1 6
# Short-Description: initscript for teamcity-agent
# Description:       initscript for teamcity-agent
### END INIT INFO

# Author: Alexey Efimov <aefimov-box@ya.ru>

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
AGENTS_ROOT="/usr/local/teamcity-agents"
DATA_ROOT="/var/lib/teamcity/BuildAgents"

detect_user() {
    # Get agent's work dir owner
    stat -c '%U' "$AGENTS_ROOT/$1"
}

d_start() {
    su - $(detect_user $1) -c "(. ~/.teamcityrc; cd $AGENTS_ROOT/$1; $AGENTS_ROOT/$1/bin/agent.sh start)"
}

d_stop() {
    su - $(detect_user $1) -c "(. ~/.teamcityrc; cd $AGENTS_ROOT/$1; $AGENTS_ROOT/$1/bin/agent.sh stop kill)"
}

d_install() {
    NAME=$1
    SERVER_URL=$2
    AGENT_USER=${3:-"teamcity"}
    if [ -z "$NAME" -o -z "$SERVER_URL" ]; then
        echo "Usage /etc/init.d/teamcity-agent install <teamcity-agent-name> <teamcity.server.url> [<user>]"
        exit 1;
    else
        echo Downloading TeamCity Agent from $SERVER_URL...
        BUILD_AGENT_ZIP="buildAgent.zip"
        wget --no-check-certificate -O $AGENTS_ROOT/$BUILD_AGENT_ZIP $SERVER_URL/update/$BUILD_AGENT_ZIP
        unzip $AGENTS_ROOT/$BUILD_AGENT_ZIP -d $AGENTS_ROOT/$NAME
        chmod +x $AGENTS_ROOT/$NAME/bin/agent.sh
        WORK_DIR="$DATA_ROOT/$NAME/work"
        TEMP_DIR="$DATA_ROOT/$NAME/temp"
        SYSTEM_DIR="$DATA_ROOT/$NAME/system"
        OWN_PORT="9090"
        MAX_EXISTS_PORT=$(cat $AGENTS_ROOT/*/conf/buildAgent.properties 2>/dev/null | grep ownPort | cut -d= -f2 | sort -r | head -1)
        if [ ! -z "$MAX_EXISTS_PORT" ]; then
            OWN_PORT=$(expr $MAX_EXISTS_PORT + 1)
        fi

        cat $AGENTS_ROOT/$NAME/conf/buildAgent.dist.properties \
            | sed "s,^serverUrl=.*$,serverUrl=$SERVER_URL,g" \
            | sed "s,^name=.*$,name=$NAME,g" \
            | sed "s,^workDir=.*$,workDir=$WORK_DIR,g" \
            | sed "s,^tempDir=.*$,tempDir=$TEMP_DIR,g" \
            | sed "s,^systemDir=.*$,systemDir=$SYSTEM_DIR,g" \
            | sed "s,^ownPort=.*$,ownPort=$OWN_PORT,g" \
        > $AGENTS_ROOT/$NAME/conf/buildAgent.properties
        chown -R $AGENT_USER $AGENTS_ROOT/$NAME
        echo "Agent installed to $AGENTS_ROOT/$NAME with follow options:"
        cat $AGENTS_ROOT/$NAME/conf/buildAgent.properties | egrep -v "^#" | egrep -v "^[[:space:]]*$"
        echo "To start/stop/restart agent use:"
        echo "sudo /etc/init.d/teamcity-agent (start|stop|restart) $NAME"
    fi
}

teamcity_agent_name="$2"
if [ -z "$teamcity_agent_name" ]; then
    teamcity_agent_name="buildAgent"
fi

case "$1" in
    start)
        echo "Starting TeamCity Agent '$teamcity_agent_name'..."
        d_start $teamcity_agent_name
        ;;
    stop)
        echo "Stopping TeamCity Agent '$teamcity_agent_name'..."
        d_stop $teamcity_agent_name
        ;;
    restart|force-reload)
        echo "Restarting TeamCity Agent '$teamcity_agent_name'..."
        d_stop $teamcity_agent_name
        sleep 1
        d_start $teamcity_agent_name
        ;;
    list)
        find $AGENTS_ROOT -maxdepth 1 -mindepth 1 -type d -printf '%f\n' | sort
        ;;
    install)
        shift
        echo "Installing new agent $1 connected to $2"
        d_install $1 $2 $3
        ;;
    *)
        echo "Usage: /etc/init.d/teamcity-agent {start|stop|restart|install} [<teamcity-agent-name>] [<teamcity.server.url>] [<user>]" >&2
        exit 1
        ;;
esac

exit 0
